In [1]:
import pandas as pd

In [3]:
bc = pd.read_csv(r"C:\hp\Breast_Cancer.csv")

In [8]:
bc.head(10)

,Unnamed: 0,Id,Cl.thickness,Cell.size,Cell.shape,Marg.adhesion,Epith.c.size,Bare.nuclei,Bl.cromatin,Normal.nucleoli,Mitoses,Class
0,1,1000025,5,1,1,1,2,1.0,3,1,1,benign
1,2,1002945,5,4,4,5,7,10.0,3,2,1,benign
2,3,1015425,3,1,1,1,2,2.0,3,1,1,benign
3,4,1016277,6,8,8,1,3,4.0,3,7,1,benign
4,5,1017023,4,1,1,3,2,1.0,3,1,1,benign
5,6,1017122,8,10,10,8,7,10.0,9,7,1,malignant
6,7,1018099,1,1,1,1,2,10.0,3,1,1,benign
7,8,1018561,2,1,2,1,2,1.0,3,1,1,benign
8,9,1033078,2,1,1,1,2,1.0,1,1,5,benign
9,10,1033078,4,2,1,1,2,1.0,2,1,1,benign

In [9]:
bc.shape

(699, 12)

In [7]:
bc.isnull().sum()

Unnamed: 0          0
Id                  0
Cl.thickness        0
Cell.size           0
Cell.shape          0
Marg.adhesion       0
Epith.c.size        0
Bare.nuclei        16
Bl.cromatin         0
Normal.nucleoli     0
Mitoses             0
Class               0
dtype: int64

In [16]:
bc.rename(columns ={'Cl.thickness': 'Cl_thickness' , 'Cell.size' : 'Cell_size' , 'Bare.nuclei': 'Bare_nuclei'}  , inplace = True)
bc.rename(columns ={'Cell.shape': 'Cell_shape' , 'Marg.adhesion' : 'Marg_adhesion' , 'Epith.c.size' : 'Epith_c_size'} , inplace = True)
bc.rename(columns ={'Bl.cromatin' : 'Bl_cromatin' ,  'Normal.nucleoli' : 'Normal_nucleoli'} , inplace = True)

In [22]:
bc.head(10)

,Unnamed: 0,Id,Cl_thickness,Cell_size,Cell_shape,Marg_adhesion,Epith_c_size,Bare_nuclei,Bl_cromatin,Normal_nucleoli,Mitoses,Class
0,1,1000025,5,1,1,1,2,1.0,3,1,1,benign
1,2,1002945,5,4,4,5,7,10.0,3,2,1,benign
2,3,1015425,3,1,1,1,2,2.0,3,1,1,benign
3,4,1016277,6,8,8,1,3,4.0,3,7,1,benign
4,5,1017023,4,1,1,3,2,1.0,3,1,1,benign
5,6,1017122,8,10,10,8,7,10.0,9,7,1,malignant
6,7,1018099,1,1,1,1,2,10.0,3,1,1,benign
7,8,1018561,2,1,2,1,2,1.0,3,1,1,benign
8,9,1033078,2,1,1,1,2,1.0,1,1,5,benign
9,10,1033078,4,2,1,1,2,1.0,2,1,1,benign

In [19]:
bc.Bare_nuclei.fillna(bc.Bare_nuclei.mean()  , inplace = True)

In [20]:
bc.isnull().sum()

Unnamed: 0         0
Id                 0
Cl_thickness       0
Cell_size          0
Cell_shape         0
Marg_adhesion      0
Epith_c_size       0
Bare_nuclei        0
Bl_cromatin        0
Normal_nucleoli    0
Mitoses            0
Class              0
dtype: int64

In [21]:
bc.select_dtypes(include = 'object').columns

Index(['Class'], dtype='object')

In [24]:
bc.Class.replace({'benign': 0 ,'malignant' :1 }  , inplace = True)

In [25]:
bc.head(10)

,Unnamed: 0,Id,Cl_thickness,Cell_size,Cell_shape,Marg_adhesion,Epith_c_size,Bare_nuclei,Bl_cromatin,Normal_nucleoli,Mitoses,Class
0,1,1000025,5,1,1,1,2,1.0,3,1,1,0
1,2,1002945,5,4,4,5,7,10.0,3,2,1,0
2,3,1015425,3,1,1,1,2,2.0,3,1,1,0
3,4,1016277,6,8,8,1,3,4.0,3,7,1,0
4,5,1017023,4,1,1,3,2,1.0,3,1,1,0
5,6,1017122,8,10,10,8,7,10.0,9,7,1,1
6,7,1018099,1,1,1,1,2,10.0,3,1,1,0
7,8,1018561,2,1,2,1,2,1.0,3,1,1,0
8,9,1033078,2,1,1,1,2,1.0,1,1,5,0
9,10,1033078,4,2,1,1,2,1.0,2,1,1,0

In [26]:
bc = bc.drop(['Unnamed: 0' , 'Id']  , axis = 1)

In [27]:
bc.head(10)

,Cl_thickness,Cell_size,Cell_shape,Marg_adhesion,Epith_c_size,Bare_nuclei,Bl_cromatin,Normal_nucleoli,Mitoses,Class
0,5,1,1,1,2,1.0,3,1,1,0
1,5,4,4,5,7,10.0,3,2,1,0
2,3,1,1,1,2,2.0,3,1,1,0
3,6,8,8,1,3,4.0,3,7,1,0
4,4,1,1,3,2,1.0,3,1,1,0
5,8,10,10,8,7,10.0,9,7,1,1
6,1,1,1,1,2,10.0,3,1,1,0
7,2,1,2,1,2,1.0,3,1,1,0
8,2,1,1,1,2,1.0,1,1,5,0
9,4,2,1,1,2,1.0,2,1,1,0

In [28]:
from sklearn.model_selection  import train_test_split
bc_train ,bc_test = train_test_split(bc , test_size = .2)

In [29]:
bc_train_x = bc_train.iloc[: , 0:-1]
bc_train_y = bc_train.iloc[: , -1]

In [30]:
bc_test_x = bc_test.iloc[: , 0:-1]
bc_test_y = bc_test.iloc[: , -1]

In [31]:
from sklearn.linear_model  import   LogisticRegression 

logreg = LogisticRegression()

logreg.fit ( bc_train_x  ,  bc_train_y)

LogisticRegression()

In [32]:
pred = logreg.predict(bc_test_x)

In [33]:
from sklearn.metrics import confusion_matrix

In [34]:
tab1 = confusion_matrix(bc_test_y, pred )

In [35]:
tab1

array([[89,  2],
       [ 3, 46]], dtype=int64)

In [36]:
tab1.diagonal().sum() *  100 / tab1.sum()

96.42857142857143

In [38]:
from sklearn.metrics  import recall_score
recall_score(bc_test_y  ,  pred) * 100

93.87755102040816

In [39]:
from sklearn.metrics  import f1_score
f1_score(bc_test_y  ,  pred) * 100

94.84536082474227

In [40]:
from sklearn.metrics  import precision_score
precision_score(bc_test_y  ,  pred) * 100

95.83333333333334

In [ ]:
pip install matplotlib